version: 0.0
os: linux
files:
  - source: springboot-0.0.1-SNAPSHOT.war
    destination: /home/ec2-user
  - source: start_server.sh
    destination: /home/ec2-user
  - source: appspec.yml
    destination: /home/ec2-user
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: root
